import Head from "next/head";
import Image from "next/image";
import styles from "/styles/Home.module.css";
import React from 'react';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <div className={styles.header}>
          <nav>
          <h2> <span className= {styles.halfa}>Sex</span>
              <span className= {styles.halfb}>equity</span> </h2>
            <ul>
              <li>
                {" "}
                <a href="http://localhost:3000/home">Home</a>
              </li>
              <li>
                {" "}
                <a href="http://localhost:3000/resources/resources">
                  Resources
                </a>
              </li>
              <li>
                {" "}
                <a href="http://localhost:3000/education/education">
                  Education
                </a>
              </li>
            </ul>
            <button className={styles.button}>
              {" "}
              <a href="http://localhost:3000/login/login"> My SexEquity</a>
            </button>{" "}
          </nav>
        </div>
        <title>Sexequity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <h1 className={styles.title}>
          <a>My SexEquity</a>
      </h1>
      <h2 className={styles.subtitle}>
          <a>My Learning Goals</a>
        </h2>
        <p className={styles.description2}>Choose the topics you want to learn about! Click on their name to go straight to the topics you chose.</p> 
        <p className={styles.description3}>
        <input type="checkbox" /> <a href="http://localhost:3000/education/sex/sex" className={styles.link}> Sex</a>
        <input type="checkbox" /> <a href="http://localhost:3000/education/sexual-health/sexual-health" className={styles.link}> Sexual Health</a>
        <input type="checkbox" /> <a href="http://localhost:3000/education/masturbation&porn/masturbation&porn" className={styles.link}> Masturbation & Porn</a> <br></br>
        <input type="checkbox" /> <a href="http://localhost:3000/education/contraception/contraception" className={styles.link}> Contraception</a> 
        <input type="checkbox" /> <a href="http://localhost:3000/education/consent/consent" className={styles.link}> Consent</a>
        <input type="checkbox" /> <a href="http://localhost:3000/education/pregnancy/pregnancy" className={styles.link}> Pregnancy</a>
        <input type="checkbox" /> <a href="http://localhost:3000/education/relationships/relationships" className={styles.link}> Relationships</a> 
        </p>
        <h2 className={styles.subtitle}>
          <a>My Progress</a>
        </h2>
        <p className={styles.description2}>Here you can see which Quizzes you already mastered!</p> 
        <h2 className={styles.subtitle}>
          <a>My Badges</a>
        </h2>
        <p className={styles.description2}> 
        
        </p>
        <p className={styles.description2}>Congrats! You are an experts on these topics. </p> 
        

      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.linkedin.com/in/lisa-geist-0018b91a2/"
          target="_blank"
          rel="noopener noreferrer"
        >
          <p>Powered by&nbsp;Schrade & Geist</p>
        </a>
      </footer>
    </div>
  );
}