import Head from "next/head";
import Image from "next/image";
import styles from "/styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <div className={styles.header}>
          <nav>
            <h2> <span className= {styles.halfa}>Sex</span>
              <span className= {styles.halfb}>equity</span> </h2>
            <ul>
              <li>
                {" "}
                <a href="http://localhost:3000/home">Home</a>
              </li>
              <li>
                {" "}
                <a href="http://localhost:3000/resources/resources">
                  Resources
                </a>
              </li>
              <li>
                {" "}
                <a href="http://localhost:3000/education/education">
                  Education
                </a>
              </li>
            </ul>
            <button className={styles.button}>
              {" "}
              <a href="http://localhost:3000/login/login"> My SexEquity</a>
            </button>{" "}
          </nav>
        </div>
        <title>Sexequity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a>What is Sex?</a>
        </h1>
        <p className={styles.description2}>
        Sex is when two people engage in sexual activity with each other.
        This can include things like kissing, touching, and intercourse.
        It's important to make sure that both people involved have consented and are comfortable and happy with what's happening. <code className={styles.code}></code>
        </p>
        <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSdvH4SfPWF-ssbZft4rQZTkJ4e420LeSVjg-MYNXa3Sli0Qhw/viewform?embedded=true" width="640" height="464" frameBorder="0" marginHeight="0" marginWidth="0">Wird geladen…</iframe>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.linkedin.com/in/lisa-geist-0018b91a2/"
          target="_blank"
          rel="noopener noreferrer"
        >
          <p>Powered by&nbsp;Schrade & Geist</p>
        </a>
      </footer>
    </div>
  );
}
