import Head from "next/head";
import Image from "next/image";
import styles from "/styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <div className={styles.header}>
          <nav>
          <h2> <span className= {styles.halfa}>Sex</span>
              <span className= {styles.halfb}>equity</span> </h2>
            <ul>
              <li>
                {" "}
                <a href="http://localhost:3000/home">Home</a>
              </li>
              <li>
                {" "}
                <a href="http://localhost:3000/resources/resources">
                  Resources
                </a>
              </li>
              <li>
                {" "}
                <a href="http://localhost:3000/education/education">
                  Education
                </a>
              </li>
            </ul>
            <button className={styles.button}>
              {" "}
              <a href="http://localhost:3000/login/login"> My SexEquity</a>
            </button>
          </nav>
        </div>
        <title>Sexequity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <h1 className={styles.title}>
          <a>Why does Sexual Health matter?</a>
        </h1>
        <p className={styles.description2}> Sexual health is an important part of overall health and well-being. It is important to understand and take care of your sexual health.<br></br>
        One way to take care of your sexual health is to practice safe sex. This means using condoms or other types of birth control to prevent pregnancy and protect against sexually transmitted infections (STIs). <a href="http://localhost:3000/education/contraception/contraception2" className={styles.link}>Condoms</a> can be easily found at many stores and can be used for both vaginal and anal sex. It's important to use them when you have sex with someone that didn't get tested recently.<br></br><br></br>
        Another important aspect of sexual health is getting regular check-ups. This means going to a doctor or a health clinic to <a href="http://localhost:3000/education/sexual-health/sexual-health3" className={styles.link}>get tested for STIs</a> and to talk about any concerns you may have. It's also important to talk to your doctor about any questions you may have about your sexual health.<br></br><br></br>
        It's also important to remember that you have the <a href="http://localhost:3000/education/consent/consent2" className={styles.link}>right to say "no" to any sexual activity</a> you're not comfortable with. It's important to communicate with your partner and to make sure that you are both on the same page.<br></br><br></br>
        In conclusion, taking care of your sexual health is important for your overall health and well-being. Remember to practice safe sex, get regular check-ups, communicate with your partner and respect everyone's sexual orientation and gender identity. If you have any questions or concerns, don't hesitate to talk to a trusted adult or a healthcare professional.<code className={styles.code}></code>
        <br></br><br></br>
        <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSej2z4HnDww4nN0UtZprDClUOnexcVNgDmlgRDvmGrB8wjclA/viewform?embedded=true" width="640" height="922" frameBorder="0" marginHeight="0" marginWidth="0" className={styles.questions}>Wird geladen…</iframe>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.linkedin.com/in/lisa-geist-0018b91a2/"
          target="_blank"
          rel="noopener noreferrer"
        >
          <p>Powered by&nbsp;Schrade & Geist</p>
        </a>
      </footer>
    </div>
  );
}