import Head from "next/head";
import Image from "next/image";
import styles from "/styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <div className={styles.header}>
          <nav>
          <h2> <span className= {styles.halfa}>Sex</span>
              <span className= {styles.halfb}>equity</span> </h2>
            <ul>
              <li>
                {" "}
                <a href="http://localhost:3000/home">Home</a>
              </li>
              <li>
                {" "}
                <a href="http://localhost:3000/resources/resources">
                  Resources
                </a>
              </li>
              <li>
                {" "}
                <a href="http://localhost:3000/education/education">
                  Education
                </a>
              </li>
            </ul>
            <button className={styles.button}>
              {" "}
              <a href="http://localhost:3000/login/login"> My SexEquity</a>
            </button>
          </nav>
        </div>
        <title>Sexequity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <h1 className={styles.title}>
          <a>STI Testing</a> <br></br><br></br>
        </h1>
        <h2 className={styles.subtitle}>
          <a>Why does testing for sexually transmitted diseases matter?</a>
        </h2>
        <p className={styles.description2}>Testing for sexually transmitted infections (STIs) is important because it can help you know if you have an STI and get treatment if you do. It's a way to take care of your sexual health and make sure you're healthy.<code className={styles.code}></code>
        </p>
        <h2 className={styles.subtitle}>
          <a>Where can you get tested and How does it work?</a>
        </h2>
        <p className={styles.description2}>You can get tested for STIs at a doctor's office, a health clinic, or a health department. The test is usually simple and painless. They may check your genitals or take a blood or urine sample. It's important to tell the doctor or nurse if you have any symptoms or concerns.<br></br>
        It's important to remember that there is no need to be scared about getting tested for STIs. The people at the doctor's office, health clinic, or health department are there to help you and keep your information private. It's also important to know that many people get STIs and it's nothing to be ashamed of.<code className={styles.code}></code>
        If you do have an STI, the doctor or nurse will give you medicine to help you feel better. They may also give you advice on how to protect yourself and your partner in the future.<br></br>
        </p>
        <h2 className={styles.subtitle}>
          <a>Summary</a>
        </h2>
        <p className={styles.description2}>
        In summary, testing for STIs is important to take care of your sexual health. You can get tested at a doctor's office, a health clinic, or a health department. The test is usually simple and painless. There is no need to be scared about getting tested for STIs, and if you do have an STI, the doctor or nurse will give you medicine and advice to help you feel better.
        <code className={styles.code}></code>
        <iframe src="https://docs.google.com/forms/d/e/1FAIpQLScYRAPqpZ7FieDmszXCIwwJsuWn0dE1DLXCgUaXABFkDaph3w/viewform?embedded=true" width="640" height="922" frameborder="0" marginheight="0" marginwidth="0" className={styles.questions}>Wird geladen…</iframe>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.linkedin.com/in/lisa-geist-0018b91a2/"
          target="_blank"
          rel="noopener noreferrer"
        >
          <p>Powered by&nbsp;Schrade & Geist</p>
        </a>
      </footer>
    </div>
  );
}