import Head from "next/head";
import Image from "next/image";
import styles from "/styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <div className={styles.header}>
          <nav>
          <h2> <span className= {styles.halfa}>Sex</span>
              <span className= {styles.halfb}>equity</span> </h2>
            <ul>
              <li>
                {" "}
                <a href="http://localhost:3000/home">Home</a>
              </li>
              <li>
                {" "}
                <a href="http://localhost:3000/resources/resources">
                  Resources
                </a>
              </li>
              <li>
                {" "}
                <a href="http://localhost:3000/education/education">
                  Education
                </a>
              </li>
            </ul>
            <button className={styles.button}>
              {" "}
              <a href="http://localhost:3000/login/login"> My SexEquity</a>
            </button>
          </nav>
        </div>
        <title>Sexequity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <h1 className={styles.title}>
          <a>What you need to know about <br></br> Sexually Transmitted Infections<br></br> (STIs) </a>
        </h1> 
        <p className={styles.description2}>Sexually transmitted infections (STIs) are sicknesses that you can get from having sex. They are caused by bacteria or viruses and can affect both males and females.<br></br>
        Some of the most common STIs are:<br></br><br></br>
        - Chlamydia<br></br>
        - Gonorrhea<br></br>
        - Human papillomavirus (HPV)<br></br>
        - Herpes<br></br>
        - Syphilis<br></br><br></br>
STIs can cause different symptoms, but some common ones include:<br></br><br></br>
- Pain or burning when you pee<br></br>
- Sores or bumps on or around your genitals<br></br>
- Itching or burning in your genitals<br></br>
- Discharge from your genitals<br></br>
- Rashes or sore on your genitals<br></br><br></br>
If you think you might have an STI, it's important to go to a doctor or a health clinic as soon as possible. They can do tests to see if you have an STI and give you medicine to help you feel better. It's also important to let your partner know, so they can get checked too.<br></br><br></br>
It's also important to practice safe sex by using condoms or other forms of <a href="http://localhost:3000/education/contraception/contraception2" className={styles.link}>contraceptives</a> to protect yourself and your partner from STIs. 
<code className={styles.code}></code><br></br><br></br>
<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSeeCiHzsK6rd-QpqLV3W5jkDZkj22iNyuTyUZi8dmOFBjHPsw/viewform?embedded=true" width="640" height="900" frameborder="0" marginheight="0" marginwidth="0" className={styles.questions}>Wird geladen…</iframe>        
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.linkedin.com/in/lisa-geist-0018b91a2/"
          target="_blank"
          rel="noopener noreferrer"
        >
          <p>Powered by&nbsp;Schrade & Geist</p>
        </a>
      </footer>
    </div>
  );
}