import Head from "next/head";
import Image from "next/image";
import styles from "/styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
        <Head>
        <div className={styles.header}>
          <nav>
            <h2 className={styles.logo}>SexEquity</h2>
            <ul>
              <li>
                {" "}
                <a href="http://localhost:3000/home">Home</a>
              </li>
              <li>
                {" "}
                <a href="http://localhost:3000/resources/resources">
                  Resources
                </a>
              </li>
              <li>
                {" "}
                <a href="http://localhost:3000/education/education">
                  Education
                </a>
              </li>
            </ul>
            <button className={styles.button}>
              {" "}
              <a href="http://localhost:3000/login/login"> My SexEquity</a>
            </button>
          </nav>
        </div>
        <title>Sexequity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <main className={styles.main}>
        <h1 className={styles.title}>
        <a>Login</a>
        </h1>
        <br/>
        <h1 className={styles.title}>
          <a>Register</a>
        </h1>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
          <form>

              <label htmlFor="Name">Name:</label>&nbsp;
                <input type="Name" id="Name" name="Name" required/> 
                  <br/>
                  <br/>
              <label htmlFor="email">Email:</label>&nbsp;
                <input type="email" id="email" name="email" required/>
                  <br/>
                  <br/>
               <label htmlFor="password">Password:</label>&nbsp;
             <input type="password" id="password" name="password" required/>
            <br/>
            <br/>
            <button type="submit"> </button>
            &nbsp;
            <label>I am 18 years or older</label>
            <br/>
            <button type="submit"> </button>
            &nbsp;
            <label>I have read and accept the website's terms and conditions, including the privacy policy.</label>

            </form>

        </main>
            <footer className={styles.footer}>
            <a
              href="https://www.linkedin.com/in/lisa-geist-0018b91a2/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <p>Powered by&nbsp;Schrade & Geist</p>
            </a>
          </footer>
        </div>
      );
    }
