import Head from "next/head";
import Image from "next/image";
import styles from "styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
    <Head>
        <div className={styles.header}>
          <nav>
            <h2 className={styles.logo}>SexEquity</h2>
            <ul>
              <li>
                {" "}
                <a href="http://localhost:3000/home">Home</a>
              </li>
              <li>
                {" "}
                <a href="http://localhost:3000/resources/resources">
                  Resources
                </a>
              </li>
              <li>
                {" "}
                <a href="http://localhost:3000/education/education">
                  Education
                </a>
              </li>
            </ul>
            <button className={styles.button}>
              {" "}
              <a href="http://localhost:3000/login/login"> My SexEquity</a>
            </button>
          </nav>
        </div>
        <title>Sexequity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a>Sexequity</a>
        </h1>

        <p className={styles.description}>
          Your website to help you learn about Sex and find the right assistance
          for you. <code className={styles.code}></code>
        </p>

        <div className={styles.grid}>
          <a
            href="http://localhost:3000/education/education"
            className={styles.card}
          >
            <h2>Education</h2>
            <p>Everything you want to know about Sex.</p>
          </a>

          <a
            href="http://localhost:3000/resources/resources"
            className={styles.card}
          >
            <h2>Find Resources</h2>
            <p>Do you need sexual assistance?</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Get urgent help.</h2>
            <p>
              Is someone doing something sexual you do not like? You can find
              help here!
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Impressum</h2>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.linkedin.com/in/gesine-schrade/"
          target="_blank"
          rel="noopener noreferrer"
        >
          <p> Powered by&nbsp;Schrade & Geist</p>
        </a>
      </footer>
    </div>
  );
}
