import Head from "next/head";
import Image from "next/image";
import styles from "/styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
      <div className={styles.header}>
          <nav>
            <h2 className={styles.logo}>SexEquity</h2>
            <ul>
              <li>
                {" "}
                <button className={styles.button}>
                <a href="http://localhost:3000/home">Home</a>
                </button>
              </li>
              <li>
                {" "}
                <button className={styles.button}>
                <a href="http://localhost:3000/resources/resources">
                  Resources
                </a>
                </button>
              </li>
              <li>
              <button className={styles.button}>
                {" "}
                <a href="http://localhost:3000/education/education">Education</a>
                </button>
              </li>
            </ul>
            <button className={styles.button}>
              {" "}
              <a href="http://localhost:3000/login/login"> My SexEquity</a>
            </button>
          </nav>
        </div>
        <title>Sexequity - Resources</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a>What are service Providers?</a>
        </h1>

        <div className={styles.grid}>
        <p className={styles.description}>
        Service sex providers for people with disabilities are individuals
              or businesses that offer sexual services specifically to people
              with disabilities. These services may be provided in person or
              remotely, and they may include things like sensual massages,
              companionship, or other forms of sexual activity. <code className={styles.code}></code>
        </p>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.linkedin.com/in/lisa-geist-0018b91a2/"
          target="_blank"
          rel="noopener noreferrer"
        >
          <p>Powered by&nbsp;Schrade & Geist</p>
        </a>
      </footer>
    </div>
  );
}