import Head from "next/head";
import Image from "next/image";
import styles from "/styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
     <Head>
        <div className={styles.header}>
          <nav>
          <h2> <span className= {styles.halfa}>Sex</span>
              <span className= {styles.halfb}>equity</span> </h2>
            <ul>
              <li>
                {" "}
                <a href="http://localhost:3000/home">Home</a>
              </li>
              <li>
                {" "}
                <a href="http://localhost:3000/resources/resources">
                  Resources
                </a>
              </li>
              <li>
                {" "}
                <a href="http://localhost:3000/education/education">
                  Education
                </a>
              </li>
            </ul>
            <button className={styles.button}>
              {" "}
              <a href="http://localhost:3000/login/login"> My SexEquity</a>
            </button>
          </nav>
        </div>
        <title>Sexequity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a>Resources</a>
        </h1>

        <p className={styles.description}>
          You want to learn about service providers or where you can find them,
          look below! <code className={styles.code}></code>
        </p>

        <div className={styles.grid}>
          <a
            href="http://localhost:3000/resources/serviceprov"
            className={styles.card}
          >
            <h2>What are Service Providers &rarr;</h2>
          </a>

          <a
            href="http://localhost:3000/resources/findprov"
            className={styles.card}
          >
            <h2>Find Service Providers &rarr;</h2>
          </a>

          <a
            href="http://localhost:3000/resources/toys"
            className={styles.card}
          >
            <h2>Sex Toys &rarr;</h2>
          </a>

          <a
            href="https://www.berlin.de/lb/psychiatrie/hilfe-in-krisen/weitere-krisen-und-notrufnummern-fuer-erwachsene/"
            className={styles.card}
          >
            <h2>Emergency Number &rarr;</h2>
            <p>555 15234 00</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.linkedin.com/in/lisa-geist-0018b91a2/"
          target="_blank"
          rel="noopener noreferrer"
        >
          <p>Powered by&nbsp;Schrade & Geist</p>
        </a>
      </footer>
    </div>
  );
}
