import Head from "next/head";
import Image from "next/image";
import styles from "/styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sexequity - Resources</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a>Resources</a>
        </h1>

        <p className={styles.description}>
          You want to learn about service providers or where you can find them,
          look below! <code className={styles.code}></code>
        </p>

        <div className={styles.grid}>
          <a
            href="http://localhost:3000/resources/serviceprov"
            className={styles.card}
          >
            <h2>What are Service Providers &rarr;</h2>
          </a>

          <a
            href="https://www.google.de/maps/search/sexual+therapist+berlin/@52.5387346,13.3243523,13z"
            className={styles.card}
          >
            <h2>Find Service Providers &rarr;</h2>
          </a>

          <a
            href="http://localhost:3000/resources/toys"
            className={styles.card}
          >
            <h2>Sex Toys and Pornos &rarr;</h2>
          </a>

          <a
            href="https://www.berlin.de/lb/psychiatrie/hilfe-in-krisen/weitere-krisen-und-notrufnummern-fuer-erwachsene/"
            className={styles.card}
          >
            <h2>Emergency Number &rarr;</h2>
            <p>555 15234 00</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.linkedin.com/in/lisa-geist-0018b91a2/"
          target="_blank"
          rel="noopener noreferrer"
        >
          <p>Powered by&nbsp;Schrade & Geist</p>
        </a>
      </footer>
    </div>
  );
}
