import Head from "next/head";
import Image from "next/image";
import styles from "/styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
      <div className={styles.header}>
          <nav>
            <h2 className={styles.logo}>SexEquity</h2>
            <ul>
              <li>
                {" "}
                <button className={styles.button}>
                <a href="http://localhost:3000/home">Home</a>
                </button>
              </li>
              <li>
                {" "}
                <button className={styles.button}>
                <a href="http://localhost:3000/resources/resources">
                  Resources
                </a>
                </button>
              </li>
              <li>
              <button className={styles.button}>
                {" "}
                <a href="http://localhost:3000/education/education">Education</a>
                </button>
              </li>
            </ul>
            <button className={styles.button}>
              {" "}
              <a href="http://localhost:3000/login/login"> My SexEquity</a>
            </button>
          </nav>
        </div>
        <title>Sexequity - Resources</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          What are <a>Service Providers</a>
        </h1>

        <p className={styles.description}>
          We explain you a litte what kind of service providers exist.{" "}
          <code className={styles.code}></code>
        </p>

        <div className={styles.grid}>
          <a
            href="https://www.aktion-mensch.de/menschen-und-geschichten/aus-dem-leben/sexualassistenz"
            className={styles.card}
            >
            <h2>Explanations &rarr;</h2>
            <p className={styles.hidden}>
              Service sex providers for people with disabilities are individuals
              or businesses that offer sexual services specifically to people
              with disabilities. These services may be provided in person or
              remotely, and they may include things like sensual massages,
              companionship, or other forms of sexual activity.
            </p>
          </a>

          <a
            href="https://www.therapie.de/psychotherapie/-schwerpunkt-/sexualtherapie/"
            className={styles.card}
          >
            <h2>Sexual Therapist &rarr;</h2>
            <p>
              A sexual therapist is a person who helps people with disabilities
              learn about and enjoy their own bodies and sexuality. They may
              work with individuals or couples to explore issues related to
              intimacy and relationships, and they may use techniques like
              counseling, education, and exercises to help people with
              disabilities improve their sexual well-being.
            </p>
          </a>

          <a
            href="https://cordis.europa.eu/article/id/174984-understanding-sexual-assistance-for-the-disabled"
            className={styles.card}
          >
            <h2>Sexual assistance&rarr;</h2>
            <p>
              Sexual assistance is a type of support that helps individuals with
              disabilities engage in sexual activity or experience sexual
              pleasure. This can include things like providing physical
              assistance with positioning or movement, or helping to operate
              assistive devices. It is important to note that sexual assistance
              should always be provided in a respectful and consensual manner,
              and it is important to consider the individual needs and
              preferences of the person with a disability.
            </p>
          </a>

          <a href="https://sexualbegleitung.berlin" className={styles.card}>
            <h2>Prostituts with spezialization&rarr;</h2>
            <p>
              Prostitution is the practice of selling sexual services in
              exchange for payment. Some people with disabilities may engage in
              prostitution, either as a means of earning income or for other
              reasons. It is important to note that prostitution is a
              controversial and complex issue, and different people have
              different views on it. Some people see it as a legitimate form of
              work, while others view it as exploitative or harmful.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.linkedin.com/in/gesine-schrade/"
          target="_blank"
          rel="noopener noreferrer"
        >
          <p> Powered by&nbsp;Schrade & Geist</p>
        </a>
      </footer>
    </div>
  );
}
