import Head from "next/head";
import Image from "next/image";
import styles from "/styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <div className={styles.header}>
          <nav>
          <h2> <span className= {styles.halfa}>Sex</span>
              <span className= {styles.halfb}>equity</span> </h2>
            <ul>
              <li>
                {" "}
                <a href="http://localhost:3000/home">Home</a>
              </li>
              <li>
                {" "}
                <a href="http://localhost:3000/resources/resources">
                  Resources
                </a>
              </li>
              <li>
                {" "}
                <a href="http://localhost:3000/education/education">
                  Education
                </a>
              </li>
            </ul>
            <button className={styles.button}>
              {" "}
              <a href="http://localhost:3000/login/login"> My SexEquity</a>
            </button>
          </nav>
        </div>
        <title>Sexequity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <h1 className={styles.title}>
          <a>Methods of Contraception</a>
        </h1>
        <p className={styles.description2}>Contraceptives are methods that can help prevent pregnancy. There are many different types of contraceptives, each with its own set of pros and cons. Here are a few examples:
          <code className={styles.code}></code>
        </p>
        <h2 className={styles.subtitle}>
          <a>Condoms:</a>
        </h2>
        <p className={styles.description2}>These are thin rubber or plastic covers that go over the penis or inside the vagina. They can help prevent pregnancy by keeping the sperm from reaching the egg. Condoms also protect against sexually transmitted infections (STIs). <br></br><br></br>Pros: They are easy to use, widely available, and protect against STIs. <br></br>Cons: They need to be used every time you have sex.
          <code className={styles.code}></code>
        </p>
        <h2 className={styles.subtitle}>
          <a>Birth control pills:</a>
        </h2>
        <p className={styles.description2}>
        These are small pills that you take every day to prevent pregnancy. They work by stopping the ovaries from releasing eggs. <br></br><br></br>Pros: They are easy to use and can also help with other health issues like heavy periods. <br></br>Cons: You need to remember to take the pill every day and they don't protect against STIs.
          <code className={styles.code}></code>
        </p>
        <h2 className={styles.subtitle}>
          <a>IUD (intrauterine device):</a>
        </h2>
        <p className={styles.description2}> This is a small device that a doctor or nurse puts inside the uterus to prevent pregnancy. It can stay there for 3 to 5 years. <br></br><br></br>Pros: It's long-lasting and you don't have to remember to do anything. <br></br>Cons: It needs to be inserted and removed by a healthcare professional.
          <code className={styles.code}></code>
        </p>
        <h2 className={styles.subtitle}>
          <a>The shot:</a>
        </h2>
        <p className={styles.description2}>This is a shot that you get every 3 months to prevent pregnancy. It works by stopping the ovaries from releasing eggs.<br></br><br></br> Pros: It's long-lasting and you don't have to remember to do anything.<br></br> Cons: You need to get the shot every 3 months.<br></br><br></br>
        It's important to talk to your doctor or a healthcare professional about the different types of contraceptives and which one is the best for you. They can help you understand the pros and cons of each method and how to use them correctly.<br></br><br></br>
        In summary, contraceptives are methods that help prevent pregnancy. There are different types, like condoms, birth control pills, IUD and the shot. Each method has its own pros and cons and it's important to talk to a healthcare professional to determine which one is the best for you.
          <code className={styles.code}></code>
        </p>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://www.linkedin.com/in/lisa-geist-0018b91a2/"
          target="_blank"
          rel="noopener noreferrer"
        >
          <p>Powered by&nbsp;Schrade & Geist</p>
        </a>
      </footer>
    </div>
  );
}