import Head from "next/head";
import Image from "next/image";
import styles from "/styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <div className={styles.header}>
          <nav>
          <h2> <span className= {styles.halfa}>Sex</span>
              <span className= {styles.halfb}>equity</span> </h2>
            <ul>
              <li>
                {" "}
                <a href="http://localhost:3000/home">Home</a>
              </li>
              <li>
                {" "}
                <a href="http://localhost:3000/resources/resources">
                  Resources
                </a>
              </li>
              <li>
                {" "}
                <a href="http://localhost:3000/education/education">
                  Education
                </a>
              </li>
            </ul>
            <button className={styles.button}>
              {" "}
              <a href="http://localhost:3000/login/login"> My SexEquity</a>
            </button>
          </nav>
        </div>
        <title>Sexequity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <h1 className={styles.title}>
          <a>What is Consent?</a>
        </h1>
        <p className={styles.description2}> Consent is when someone agrees to do something. It's like asking someone if they want to play a game with you. If they say yes, that means they give their consent to play the game. If they say no, that means they don't give their consent and you shouldn't play the game with them.<br></br><br></br>
        It's important to always get consent before doing something with someone else. This is true for things like playing games, but it's also true for things like touching someone or taking their stuff. It's not okay to touch someone or take their things without asking first and getting their consent.<br></br><br></br>
        In summary, consent is when someone agrees to something and it's important to always get consent before doing something with someone else.<br></br><code className={styles.code}></code>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.linkedin.com/in/lisa-geist-0018b91a2/"
          target="_blank"
          rel="noopener noreferrer"
        >
          <p>Powered by&nbsp;Schrade & Geist</p>
        </a>
      </footer>
    </div>
  );
}